# Generated by Django 6.1.1 on 2026-09-18 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user', models.CharField(db_index=True, default='Unassigned', max_length=150, verbose_name='End-User')),
                ('device', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('All-in-One', 'All-in-One'), ('Server', 'Server'), ('Workstation', 'Workstation'), ('Other', 'Other')], default='Desktop', max_length=50, verbose_name='Device Type')),
                ('brand_model', models.CharField(max_length=150, verbose_name='Brand and Model')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Serial Number')),
                ('computer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Computer Name')),
                ('monitor_serial', models.CharField(blank=True, default='', max_length=150, verbose_name='Monitor with Serial Number')),
                ('ups_serial', models.CharField(blank=True, default='', max_length=150, verbose_name='UPS with Serial Number')),
                ('office', models.CharField(default='ODE-ICTS', max_length=150, verbose_name='Office / Section / Division')),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Available / Spare', 'Available / Spare'), ('Under Repair', 'Under Repair'), ('Decommissioned', 'Decommissioned')], db_index=True, default='In Use', max_length=50)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=50, verbose_name='Property / Asset Tag')),
                ('processor', models.CharField(blank=True, default='', max_length=150, verbose_name='Processor (CPU)')),
                ('ram', models.CharField(blank=True, default='', max_length=100, verbose_name='Memory (RAM)')),
                ('storage', models.CharField(blank=True, default='', max_length=150, verbose_name='Storage / Drive')),
                ('gpu', models.CharField(blank=True, default='', max_length=150, verbose_name='Graphics')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='Operating System')),
                ('notes', models.TextField(blank=True, default='', verbose_name='General Remarks / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer Asset',
                'verbose_name_plural': 'Computer Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Ref. No.')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('section_division', models.CharField(default='ODE-ICTS', max_length=150, verbose_name='Section/Division')),
                ('date_of_filing', models.CharField(max_length=50, verbose_name='Date of Filing')),
                ('contact_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Contact No.')),
                ('incident_description', models.TextField(verbose_name='Brief description of the Incident or Request')),
                ('hardware_type', models.CharField(default='Desktop', max_length=50, verbose_name='Hardware Type')),
                ('hardware_brand_model', models.CharField(max_length=150, verbose_name='Brand and Model')),
                ('hardware_serial_number', models.CharField(max_length=100, verbose_name='Serial Number')),
                ('hardware_computer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Computer Name')),
                ('app_software_description', models.CharField(blank=True, default='', max_length=200, verbose_name='App System / Software Description')),
                ('app_software_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Version')),
                ('connectivity_description', models.CharField(blank=True, default='', max_length=200, verbose_name='Connectivity Description')),
                ('user_account_description', models.CharField(blank=True, default='', max_length=200, verbose_name='User Account Description')),
                ('assessment', models.TextField(blank=True, default='', verbose_name='Assessment')),
                ('actions_taken', models.TextField(blank=True, default='', verbose_name='Actions Taken and/or Recommendations')),
                ('mode_of_filing', models.CharField(choices=[('Walk-in', 'Walk-in'), ('Telephone Call', 'Telephone Call'), ('Email', 'Email')], default='Walk-in', max_length=30, verbose_name='Mode of Filing')),
                ('date_time_received', models.CharField(blank=True, default='', max_length=100, verbose_name='Date and Time Received')),
                ('date_time_completed', models.CharField(blank=True, default='', max_length=100, verbose_name='Date and Time Completed')),
                ('fulfilled_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Fulfilled by (Signature over Printed Name)')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Reviewed by (Signature over Printed Name)')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting for Parts', 'Waiting for Parts'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('concern_addressed', models.CharField(blank=True, default='', max_length=10, verbose_name='Was concern addressed? (Yes/No)')),
                ('it_support_satisfaction', models.CharField(blank=True, default='', max_length=30, verbose_name='IT Support Satisfaction')),
                ('solution_satisfaction', models.CharField(blank=True, default='', max_length=30, verbose_name='Solution Effectiveness Satisfaction')),
                ('comments_suggestions', models.TextField(blank=True, default='', verbose_name='Comments and/or Suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheets', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Job Sheet',
                'verbose_name_plural': 'Job Sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
