# Generated by Django 6.1.1 on 2026-09-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(db_index=True, max_length=50, unique=True)),
                ('serial_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Workstation', 'Workstation'), ('Server', 'Server'), ('All-in-One', 'All-in-One'), ('Other', 'Other')], default='Desktop', max_length=50)),
                ('brand_model', models.CharField(max_length=150)),
                ('processor', models.CharField(blank=True, default='', max_length=150)),
                ('ram', models.CharField(blank=True, default='', max_length=100)),
                ('storage', models.CharField(blank=True, default='', max_length=150)),
                ('gpu', models.CharField(blank=True, default='', max_length=150)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('owner_name', models.CharField(default='Unassigned', max_length=150)),
                ('department', models.CharField(default='General Pool', max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Available / Spare', 'Available / Spare'), ('Under Repair', 'Under Repair'), ('Decommissioned', 'Decommissioned')], db_index=True, default='In Use', max_length=50)),
                ('purchase_date', models.CharField(blank=True, default='', max_length=50)),
                ('warranty_expiry', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer Asset',
                'verbose_name_plural': 'Computer Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting for Parts', 'Waiting for Parts'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=30)),
                ('technician_name', models.CharField(blank=True, default='', max_length=150)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('parts_replaced', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_received', models.CharField(blank=True, default='', max_length=50)),
                ('date_completed', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheets', to='inventory.asset')),
            ],
            options={
                'verbose_name': 'Job Sheet',
                'verbose_name_plural': 'Job Sheets',
                'ordering': ['-created_at'],
            },
        ),
    ]
