# Generated by Django 6.1.1 on 2026-09-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Records Unit', 'Records Unit'), ('HRMU', 'HRMU'), ('Admin Office', 'Admin Office'), ('PIO', 'PIO'), ('GSO', 'GSO'), ('ICTS', 'ICTS'), ('Quality Assurance Section', 'Quality Assurance Section'), ('Quality Assurance Laboratory', 'Quality Assurance Laboratory'), ('Maintenance Section', 'Maintenance Section'), ('Finance Section', 'Finance Section'), ('Cash Unit', 'Cash Unit'), ('ADE Office', 'ADE Office'), ('DE Office', 'DE Office'), ('Procurement Unit', 'Procurement Unit'), ('Planning & Design Section', 'Planning & Design Section'), ('Supply Management Unit', 'Supply Management Unit')], default='ICTS', max_length=150, verbose_name='Office / Section / Division'),
        ),
        migrations.AlterField(
            model_name='jobsheet',
            name='section_division',
            field=models.CharField(default='ICTS', max_length=150, verbose_name='Section/Division'),
        ),
    ]
