# Generated by Django 6.1.1 on 2026-09-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_asset_office_alter_jobsheet_section_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.CharField(choices=[('Office of the District Engineer', 'Office of the District Engineer'), ('Office of the Assistant District Engineer', 'Office of the Assistant District Engineer'), ('Procurement Unit', 'Procurement Unit'), ('PIO Staff', 'PIO Staff'), ('ICT Staff', 'ICT Staff'), ('Commission On Audit', 'Commission On Audit'), ('Administrative Section', 'Administrative Section'), ('Human Resource Management Unit', 'Human Resource Management Unit'), ('Records Management Unit', 'Records Management Unit'), ('Cash Management Unit', 'Cash Management Unit'), ('Supply and Property Management Unit', 'Supply and Property Management Unit'), ('General Services Office', 'General Services Office'), ('Finance Section', 'Finance Section'), ('Planning and Design Section', 'Planning and Design Section'), ('Construction Section', 'Construction Section'), ('Quality Assurance Section', 'Quality Assurance Section'), ('Quality Assurance Laboratory', 'Quality Assurance Laboratory'), ('Maintenance Section', 'Maintenance Section'), ('Equipment Service Unit', 'Equipment Service Unit')], default='ICT Staff', max_length=150, verbose_name='Office / Section / Division'),
        ),
    ]
