# Generated by Django 6.1.1 on 2026-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_asset_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Switch', 'Switch'), ('Router', 'Router'), ('Other', 'Other')], default='Desktop', max_length=50, verbose_name='Device Type'),
        ),
    ]
